---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Using test host
  - cp ./hosts.example hosts

  # Install dependencies
  - ansible-galaxy install -p galaxy.roles -r ./requirements.yml

script:
  # Basic role syntax check
  - ansible-playbook ./base.yml -i hosts --syntax-check
  - ansible-playbook ./firewall.yml -i hosts --syntax-check
  - ansible-playbook ./nginx.yml -i hosts --syntax-check
  - ansible-playbook ./fail2ban.yml -i hosts --syntax-check
  - ansible-playbook ./redis.yml -i hosts --syntax-check
  - ansible-playbook ./haproxy.yml -i hosts --syntax-check
  - ansible-playbook ./oracle-java.yml -i hosts --syntax-check

