---
- hosts: all
  become: true
  roles:
    - geerlingguy.php

  vars:
    php_enable_webserver: false
    php_memory_limit: "128M"
    php_max_execution_time: "90"
    php_upload_max_filesize: "256M"
    php_packages:
      - php7.1
      - php7.1-cli
      - php-common
      - php7.1-common
      - php7.1-fpm
      - php7.1-json
      - php7.1-pgsql
      - php-pgsql
      - php7.1-readline
      - php7.1-xml
      - php7.1-opcache
