- src: https://github.com/sdvcrx/ansible-role-fail2ban
  name: fail2ban
  version: master

- src: jdauphant.nginx

- src: geerlingguy.firewall

- src: geerlingguy.redis

- src: geerlingguy.haproxy

- src: williamyeh.oracle-java

- src: geerlingguy.security

- src: franklinkim.ufw

- src: kamaln7.swapfile

- src: geerlingguy.php

- src: fubarhouse.nodejs

- src: cloudalchemy.node-exporter

- src: cloudalchemy.ansible_mysqld_exporter

- src: idealista.prometheus_redis_exporter-role
