- src: https://github.com/banbanchs/ansible-role-fail2ban
  name: fail2ban
  version: master

- src: jdauphant.nginx

- src: geerlingguy.firewall

- src: geerlingguy.redis

- src: geerlingguy.haproxy

- src: williamyeh.oracle-java

- src: geerlingguy.security

- src: franklinkim.ufw

- src: kamaln7.swapfile

- src: geerlingguy.php

- src: fubarhouse.nodejs
