---
- hosts: all
  become: true

  # Thanks https://github.com/Oefenweb/ansible-swapfile
  vars:
    swapfile_file: /swapfile
    swapfile_size: 1G
    swapfile_swappiness: 10

  tasks:
    - name: SWAP | install dependencies(debian)
      apt: name="util-linux" state="present"
      when: ansible_os_family == 'Debian'

    - name: SWAP | install dependencies(CentOS)
      yum: name="util-linux" state="present"
      when: ansible_distribution == 'CentOS'

    - name: SWAP | create swap file
      command: fallocate -l {{ swapfile_size }} {{ swapfile_file }}
      register: _create_swapfile

    - name: SWAP | set swap file permissions
      file:
        path: "{{ swapfile_file }}"
        owner: root
        group: root
        mode: 0600

    - name: SWAP | mkswap
      command: mkswap {{ swapfile_file }}
      register: created
      when: _create_swapfile.changed

    - name: SWAP | enable swapfile
      command: swapon {{ swapfile_file }}
      when: created.changed

    - name: SWAP | add swapfile to /etc/fstab
      mount:
        name: none
        src: "{{ swapfile_file }}"
        fstype: swap
        opts: sw
        passno: '0'
        dump: '0'
        state: present

    - name: SWAP | configure vm.swappiness
      sysctl:
        name: vm.swappiness
        value: "{{ swapfile_swappiness }}"
        reload: true
        state: present
      when: swapfile_swappiness is defined
